server:
  port: 8094

spring:
  application:
    name: oss-server
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bmjline_cloud
    username: ??
    password: ??
    driver-class-name: org.postgresql.Driver
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

minio:
  endpoint: http://localhost:9000
  accessKey: ??
  secretKey: ??
  bucket: other
