server:
  port: 8092

spring:
  application:
    name: blog-server
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bmjline_cloud
    username: bmj
    password: bmj.123456
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#mybatis:
#  type-aliases-package: com.bmjline.blogserver.entity
#  mapper-locations: classpath:mapper/*.xml
